version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./api:/var/www:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
    environment:
      APP_ENV: dev
      
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp