version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./api:/var/www:rw,cached
    environment:
      APP_ENV: dev
      
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp