#!/bin/sh
set -e

echo "TRUSTED_PROXIES=${TRUSTED_PROXIES}
TRUSTED_HOSTS=${TRUSTED_HOSTS}
APP_ENV=${APP_ENV}
APP_SECRET=${APP_SECRET}
DB_NAME=${DB_NAME}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_VERSION=${DB_VERSION}
DB_CHARSET=${DB_CHARSET}
MAILER_DSN=${MAILER_DSN}
CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
MERCURE_URL=${MERCURE_URL}
MERCURE_PUBLIC_URL=${MERCURE_PUBLIC_URL}
MERCURE_JWT_SECRET=${MERCURE_JWT_SECRET}
JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
JWT_PASSPHRASE=${JWT_PASSPHRASE}
STRIPE_PK=${STRIPE_PK}
STRIPE_SK=${STRIPE_SK}
STRIPE_WH_SK=${STRIPE_WH_SK}
FRONT_URL=${FRONT_URL}
KYC_API_URL=${KYC_API_URL}
KYC_API_SECRET=${KYC_API_SECRET}
" > ".env"

exit 1