controllers:
    resource: ../src/Controller/
    type: annotation
    
authentication_token:
    path: /authentication_token
    methods: ['POST']

kernel:
    resource: ../src/Kernel.php
    type: annotation
