name: CI

on:
  push:
    branches:
      - master

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create false .env to test docker image
        run: |
          cp ./api/.env.example ./api/.env

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenge-api:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Set up PHP
  #     uses: shivammathur/setup-php@v3
  #     with:
  #       php-version: 7.4

  #   - name: Install dependencies
  #     run: composer install --no-dev --optimize-autoloader

  #   - name: Run tests
  #     run: php bin/phpunit

  #   - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: "joke-app-iw2" #Must be unique in Heroku
  #         heroku_email: "mohammadamine.banaei@protonmail.com"
  #         procfile: "web: JOKE_URL=${{secrets.JOKE_URL}} npm run start:prod"

      